<<<<<<< HEAD
name: Website CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: Show files
      run: ls
=======
name: Simple CI

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files
        run: echo "CI is working!"
>>>>>>> 533dd63ec7762fd49df0b989e90ffc5c1ded2586
